import Link from "next/link";
import {Checkout} from "../styles/CartStyles";
import {motion} from "framer-motion";
import {
    Content,
    StyledAbout,
    StyledAboutUsPage,
    StyledHeader,
    StyledParagraph,
    StyledResult,
} from "../styles/AboutUsStyles";
import Head from "next/head";
import styled from "styled-components";

export default function about_us() {

    //Framer motion
    const container = {
        hidden: {opacity: 0, scale: 0.8}, show: {
            opacity: 1, scale: 1, transition: {
                staggerChildren: 0.1, delayChildren: 0.4,
            }
        }
    }

    const item = {
        hidden: {opacity: 0}, show: {opacity: 1}
    }


    return (<StyledAboutUsPage>
        <Content variants={container} initial={"hidden"} animate={"show"}>
            <Head href="../styles/globals.css">
                <title>Artlet | About Us</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <StyledHeader variants={item} initial={"hidden"} animate={"show"}>OUR STORY</StyledHeader>
                <StyledParagraph variants={item} initial={"hidden"} animate={"show"}>"From art class dreams to
                    reality"</StyledParagraph>
            </div>
            <StyledAbout variants={item}>
                <div>
                    <h2>
                        Our Story
                    </h2>
                    <p>
                        It all began during our art class in the later years of our school days. We had a shared dream
                        of creating a unique product that would be truly our own. That is how we came up with the
                        concept of Artlet, our innovative wallet design. Through this project, we are now presented with
                        the opportunity to simplify people's daily lives by helping them to streamline their everyday
                        belongings and keep only the most necessary items.
                    </p>
                </div>
            </StyledAbout>
            <StyledResult variants={item}>
                <h2>Experience the Benefits</h2>
                <p>Introducing the Wallet and Keyplate, designed to not only free your pockets from bulk but also add organization and structure to your daily routine. Our products are meticulously crafted to deliver a seamless experience and simplify your life. We are thrilled to embark on this journey and eagerly anticipate your feedback and suggestions regarding our innovative products. Join us in revolutionizing the way you carry your essentials. </p>
            </StyledResult>
            <StyledImage variants={item}>
                <motion.img
                    src="https://res.cloudinary.com/darnwljyk/image/upload/v1680521775/ffff_naqhrk.jpg"
                    alt=""/>
            </StyledImage>
            <StyledGreetings variants={item}> Best wishes <br/> Eric, Jan & Colin</StyledGreetings>
            <Checkout variants={item}>
                <Link href={"/products"}>
                    <motion.button variants={item} whileHover={{scale: 1.0}}
                                   whileTap={{scale: 0.95}}>
                        Visit our Shop
                    </motion.button>
                </Link>
            </Checkout>
        </Content>
    </StyledAboutUsPage>)
}

const StyledImage = styled(motion.div)`
  text-align: center;
  justify-content: center;
  justify-self: center;

  img {
    width: 31vh;
    border-radius: 15px;
  }
`

const StyledGreetings = styled(motion.h2)`
  text-align: center;
`