import Head from "next/head";
import "react-loading-skeleton/dist/skeleton.css";
import {StyledBox, StyledH1, StyledHero, StyledImg, StyledIndex} from "../styles/IndexStyles";
import Link from "next/link";
import {motion} from "framer-motion";

export default function Home() {
    return (
        <div>
            <Head href="../styles/globals.css">
                <title>Artlet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <StyledH1>ARTLET</StyledH1>
                <StyledIndex>
                    <StyledHero>
                        <section id={"flexI"}>
                            <div>
                                <h3>Product Details:</h3>
                                <p>
                                    Thanks to the refined design <br/> and luxurious materials, <br/> the wallet fits
                                    perfectly <br/> everywhere you put it. </p>
                            </div>
                            <div>
                                <h3>Material:</h3>
                                <p>
                                    case:  100% black PLA filament <br/>
                                    rubber band: 100% polyester
                                </p>
                            </div>
                        </section>
                        <StyledImg
                            animate={{
                                x: 0,
                                y: 0,
                                scale: 1,
                                rotate: 0,
                                opacity: 1,
                            }}
                            transition={{duration: 0.7}}
                            initial={{
                                x: 0,
                                y: 500,
                                scale: 1,
                                rotate: 0,
                                opacity: 0,

                            }}>
                            <div>
                                <motion.img animate={{rotate: [3, 20], x: -30}}
                                            src="https://res.cloudinary.com/darnwljyk/image/upload/v1680424046/ff-9jvbg_2_mbgciu.png"
                                            alt=""/>
                            </div>
                        </StyledImg>
                        <StyledBox>
                            <h1>Level up your wallet</h1>
                            <p>
                                Whether you're an art lover or simply looking for a stylish upgrade to your everyday
                                wallet, this collection is sure to impress. Choose from a variety of designs and find
                                the perfect wallet to match your personal style and taste. Level up your wallet today
                                with these stunning works of art.
                            </p>
                            <Link href={'/products'}>
                                <motion.button whileHover={{scale: 1.0}}
                                               whileTap={{scale: 0.95}}>Collections

                                </motion.button>
                            </Link>
                        </StyledBox>
                    </StyledHero>
                </StyledIndex>
            </main>
        </div>
    );
}

